### ISSUE TITLE
docker Does not work

### ISSUE THREAD

**Issue by SomeAspy** [wont-stream/analytics#1]
using the following compose file:
```yml
services:
    katze:
        restart: always
        ports:
            - '127.0.0.1:2013:3000'
        volumes:
            - ./db.json:/usr/src/app/db.json
        image: ghcr.io/wont-stream/analytics:main
```

output:
```
katze-1  | error: Cannot find module "./server.js" from "/usr/src/app/index.js"
katze-1 exited with code 0
```
